### ISSUE TITLE
Send agent gem version to oas

### ISSUE THREAD

**Issue by wjessop** [Own-and-Ship/oas_agent#58]
We should send the gem version to the O&S api. This allows us to tell people in the UI/email if they're using an old version of the gem or not and prompt them to upgrade if we want them to, otherwise we just have to spam people.

The API request for this should happen once at process startup, sending the version multiple times will increase bandwidth usage over time.

**Comment by caius** [comment]
I think we should send it as a header with every request, we'll be sending a User Agent already so let's reuse that for the agent version. Ideally without increasing the length of the UA so we're not sending more data. Even if we do, HTTPS compression is pretty good these days, a few extra bytes per request won't harm.

Lets us tie specific requests to versions, rather than having to muck about in a datawarehouse finding the last version emitted for that key (which might differ if people run different versions in different environments on the same key 🙀)

**Comment by caius** [comment]
Turns out we're already sending it, but not in the standardised format.

https://github.com/Own-and-Ship/oas_agent/blob/master/lib/agent/configuration/default_source.rb#L27

Should be `product / product_version` according to [MDN User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) docs.
